apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: devops
spec:
  project: default
  source:
    repoURL: https://github.com/KseniaMonastyreva/devOps.git
    path: kubernetes
    targetRevision: lab04
  destination:
    server: https://kubernetes.default.svc
    namespace: lab03
  syncPolicy:
    automated:
      prune: true
      selfHeal: true